version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"

  webapi:
    build: 
      context: .
    ports:
      - "4200:4200"
    container_name: webapi
  
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    # volumes: 
    #   - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    command: ['nginx-debug', '-g', 'daemon off;']
    depends_on:
      [webapi]
    